---

##########################
##########################
## OpenAPI Linter rules ##
##########################
##########################

extends: spectral:oas

overrides:
  files:
    - "**/docs/config.yaml"
