name: "Workflow Dispatch"
on: push
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:

  call-lint:
    name: "Lint"
    uses: cheqd/.github/workflows/lint.yml@develop

  call-build:
    name: "Build"
    needs: call-lint
    uses: cheqd/.github/workflows/build.yml@develop
    secrets: inherit
  
  # call-test:
  #   name: "Test"
  #   needs: call-build
  #   uses: ./.github/workflows/test.yml
  #   secrets: inherit

  call-release:
    name: "Release"
    # needs: call-test
    needs: call-build
    if: ${{ github.ref_protected == true }}
    uses: cheqd/.github/workflows/release.yml@develop
    secrets: inherit
