name: "Test"
on:
  workflow_call:
defaults:
  run:
    shell: bash
permissions:
  contents: write
  packages: read

jobs:

  integration-tests:
    name: "Integration tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Load binary artifact
        uses: actions/download-artifact@v3
        with:
          name: cheqd-noded
          path: /home/runner/.local/bin

      - name: Restore binary permissions
        run: sudo chmod +x /home/runner/.local/bin/cheqd-noded

      - name: Download node Docker image
        uses: actions/download-artifact@v3
        with:
          name: cheqd-node-build.tar

      - name: Load node Docker image
        run: docker load -i cheqd-node-build.tar

      - name: Setup 4 Validators + 2 Observers Docker localnet
        working-directory: ./docker/localnet
        run: |
          bash gen-network-config.sh
          sudo chown -R 1000:1000 network-config
          CHEQD_NODE_IMAGE=${{ github.repository }} DOCKER_IMAGE_VERSION=${{ github.sha }} docker compose up -d

      - name: Check all Docker localnet nodes are active
        run: bash ./tests/tools/wait-for-chain.sh

      - name: Import keys
        working-directory: ./docker/localnet
        run: |
          bash import_keys.sh

      - uses: actions/setup-go@v3
        with:
          go-version-file: ./go.mod

      - name: Install ginkgo
        working-directory: ./..
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo@latest

      - name: Run tests
        run: |
          ginkgo -r --tags integration tests/integration
