name: "Test"
on:
  pull_request_target:
    branches:
      - main
      - develop
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - ready_for_review
      - review_requested
  workflow_call:
defaults:
  run:
    shell: bash
permissions:
  id-token: write
  contents: write
  checks: write

jobs:
  unit-tests:
    name: "Unit tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version-file: ./go.mod
          cache: true

      - name: Install ginkgo
        working-directory: ./..
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo@latest
          go install github.com/jstemmer/go-junit-report/v2@latest

      - name: Run Ginkgo tests
        run: ginkgo -r --race --randomize-all --randomize-suites --junit-report report.xml

      - uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          report_paths: 'report.xml'
