name: "Test"
on:
  workflow_call:
defaults:
  run:
    shell: bash
permissions:
  id-token: write
  contents: write
  checks: write

jobs:
  unit-tests:
    name: "Unit tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version-file: ./go.mod
          cache: true

      - name: Install ginkgo
        run: |
          go get github.com/onsi/ginkgo/v2/ginkgo
          go get github.com/onsi/gomega/...

      - name: Run Ginkgo tests
        run: ginkgo -r --race --randomize-all --randomize-suites --junit-report report.xml

      # - uses: mikepenz/action-junit-report@v3
      #   if: success() || failure()        # run this step even if previous step failed
      #   with:
      #     report_paths: 'report.xml'
